server:
  port: 8130 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置nacos注册中心地址

# 阿里云对象存储服务OSS配置（自定义配置格式）
aliyun:
  oss:
    endpoint: X
    keyId: X
    keySecret: X
    bucketName: X


